name: HuHoSTDAuthMe
version: 1.0.0
main: com.stoopad.authme.HuHoSTDAuthMe
api-version: '1.21'
author: stoopad
description: HuHoBot 扩展 - QQ群强制登陆 & 重置密码（AuthMe）

depend:
  - HuHoBot
  - HuHoSTDWhiteList
  - AuthMe

commands: {}

permissions:
  qqauth.admin:
    description: 管理权限
    default: op
